# Generated by Django 3.1 on 2022-03-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='pics/default_profile.jpg', upload_to='pics/profile_pics'),
        ),
    ]
